// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIQiCDJo9hnEwn4suagQTxplnQrGBYp4',
    appId: '1:974435598175:web:73a2f503a95cfd179600ea',
    messagingSenderId: '974435598175',
    projectId: 'gofirepod',
    authDomain: 'gofirepod.firebaseapp.com',
    storageBucket: 'gofirepod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjWA1qZu4qzkvj85Zz1byP5Uj_5QNN5M',
    appId: '1:974435598175:android:806940afad38925f9600ea',
    messagingSenderId: '974435598175',
    projectId: 'gofirepod',
    storageBucket: 'gofirepod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcf2wpvuUrnhG4cXn_KjdUMKIXdBMcY_w',
    appId: '1:974435598175:ios:8b796f7068ec869b9600ea',
    messagingSenderId: '974435598175',
    projectId: 'gofirepod',
    storageBucket: 'gofirepod.appspot.com',
    iosClientId: '974435598175-qpr3hbn84jbo3sj724rvv3e5ll4m408n.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcf2wpvuUrnhG4cXn_KjdUMKIXdBMcY_w',
    appId: '1:974435598175:ios:6b346d5eb300ec359600ea',
    messagingSenderId: '974435598175',
    projectId: 'gofirepod',
    storageBucket: 'gofirepod.appspot.com',
    iosClientId: '974435598175-45l7sovirgv84univg5q218l7g265614.apps.googleusercontent.com',
    iosBundleId: 'com.ankit.authapp',
  );
}
